apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflake-id-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-id
  template:
    metadata:
      labels:
        app: snowflake-id
    spec:
      containers:
        - name: snowflake-id
          image: snowflake-id-app:stable
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
            initialDelaySeconds: 40
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
